//! Test harness for acceptance workloads.
//!
//! This test uses datatest-stable to discover and run all workload specs in the
//! acceptance_workloads directory. Each spec file becomes its own test.

use std::path::Path;

use acceptance::acceptance_workloads::{
    test_case_from_spec_path, workload::execute_and_validate_workload,
};
use delta_kernel_benchmarks::models::{ReadExpected, SnapshotExpected, Spec};

/// Tests that cannot be executed due to test harness limitations.
/// These fail at parse time or cause infrastructure issues (OOM, hang).
/// All other failures (bugs, divergences, missing features) go in EXPECTED_KERNEL_FAILURES.
const SKIP_LIST: &[(&str, &str)] = &[
    ("DV-017/", "Huge table (2B rows) causes OOM/hang"),
    // The Spec enum only supports "read" and "snapshot" types.
    // CDF, transaction, and domain metadata specs fail at parse time.
    ("_cdf", "CDF (Change Data Feed) test type not yet supported"),
    ("_txn", "Transaction test type not yet supported"),
    (
        "_domain_metadata",
        "Domain metadata test type not yet supported",
    ),
    // These have `"type": "cdf"` which the harness cannot parse.
    (
        "cdc_err_",
        "CDF test type not yet supported (fails at parse time)",
    ),
];

fn should_skip_test(test_path: &str) -> Option<&'static str> {
    for (pattern, reason) in SKIP_LIST {
        if test_path.contains(pattern) {
            return Some(reason);
        }
    }
    None
}

/// Tests that CAN be executed but are expected to fail (kernel bugs or divergences).
/// Unlike SKIP_LIST, these workloads run and we assert they produce wrong results or errors.
/// When a kernel fix lands, the test will pass and the entry should be removed.
const EXPECTED_KERNEL_FAILURES: &[(&str, &[&str])] = &[
    // Kernel reads timestamps as Timestamp(Microsecond, Some("UTC")),
    // Spark writes expected data as Timestamp(Nanosecond, None).
    // Same instant, different Arrow representation.
    (
        "Timestamp type divergence (kernel uses Microsecond/UTC, Spark uses Nanosecond/None)",
        &[
            "cloneDeepMultiType/specs/cloneDeepMultiType_readAll",
            "cloneDeepMultiType/specs/cloneDeepMultiType_readFiltered",
            "cr_timestamp_boundaries/specs/cr_timestamp_boundaries_read_all",
            "dcscStructWithSpecialTypes/specs/dcscStructWithSpecialTypes_read_high_amount",
            "dcscStructWithSpecialTypes/specs/dcscStructWithSpecialTypes_read_by_date",
            "dcscStructWithSpecialTypes/specs/dcscStructWithSpecialTypes_read_all",
            "dpReadPartitionTimestamp/specs/dpReadPartitionTimestamp_readAll",
            "dsReadMultipleTypes/specs/dsReadMultipleTypes_readAll",
            "dsReadTimestampType/specs/dsReadTimestampType_readAll",
            "ds_datetime/specs/ds_datetime_hit_dt_eq",
            "ds_datetime/specs/ds_datetime_hit_dt_gte",
            "ds_datetime/specs/ds_datetime_hit_dt_lt",
            "ds_datetime/specs/ds_datetime_miss_dt_2023",
            "ds_datetime/specs/ds_datetime_miss_dt_2025",
            "ds_date_trunc_timestamp/specs/ds_date_trunc_timestamp_hit_trunc_month_june",
            "ds_date_trunc_timestamp/specs/ds_date_trunc_timestamp_hit_trunc_month_march",
            "ds_date_trunc_timestamp/specs/ds_date_trunc_timestamp_miss_trunc_month_jan",
            "gc_datetime/specs/gc_datetime_filter_date",
            "gc_datetime/specs/gc_datetime_read_all",
            "ntz_mixed_tz_ntz/specs/ntz_mixed_tz_ntz_filter_ntz_col",
            "ntz_mixed_tz_ntz/specs/ntz_mixed_tz_ntz_full_scan",
            "pve_timestamp_partition/specs/pve_timestamp_partition_read_all",
            "restoreCheckData/specs/restoreCheckData_filterBoolean",
            "restoreCheckData/specs/restoreCheckData_filterDecimal",
            "restoreCheckData/specs/restoreCheckData_readAll",
            "st_datetime_stats/specs/st_datetime_stats_filter_date_eq",
            "st_datetime_stats/specs/st_datetime_stats_filter_date_range",
            "st_datetime_stats/specs/st_datetime_stats_full_scan",
            "cdc_multiple_types/specs/cdc_multiple_types_read_all",
            "cdc_timestamp_tz_handling/specs/cdc_timestamp_tz_handling_read_all",
            "gc_append_data/specs/gc_append_data_read_all",
            "gc_delete/specs/gc_delete_read_all",
            "gc_insert_by_name/specs/gc_insert_by_name_read_all",
            "gc_update_source/specs/gc_update_source_read_all",
        ],
    ),
    // Kernel produces {metadata, value}, Spark produces {value, metadata}.
    (
        "Variant field order divergence (kernel {metadata,value}, Spark {value,metadata})",
        &[
            "var_001_basic/specs/var_001_basic_read_all",
            "var_001_basic/specs/var_001_basic_select_variant_col",
            "var_002_basic_stats/specs/var_002_basic_stats_read_all",
            "var_003_nested_stats/specs/var_003_nested_stats_read_all",
            "var_004_non_objects/specs/var_004_non_objects_filter_first_three",
            "var_004_non_objects/specs/var_004_non_objects_read_all",
            "var_005_null_counts/specs/var_005_null_counts_filter_non_null",
            "var_005_null_counts/specs/var_005_null_counts_read_all",
            "var_006_different_types/specs/var_006_different_types_filter_by_id",
            "var_006_different_types/specs/var_006_different_types_read_all",
            "var_007_partitions/specs/var_007_partitions_filter_partition",
            "var_007_partitions/specs/var_007_partitions_read_all",
            "var_008_many_fields/specs/var_008_many_fields_read_all",
            "var_009_unusual_chars/specs/var_009_unusual_chars_read_all",
            "var_010_nested_fields/specs/var_010_nested_fields_read_all",
            "var_011_missing_values/specs/var_011_missing_values_read_all",
            "var_012_mixed_types/specs/var_012_mixed_types_filter_half",
            "var_012_mixed_types/specs/var_012_mixed_types_read_all",
            "var_013_extreme_values/specs/var_013_extreme_values_read_all",
            "var_014_variant_in_struct/specs/var_014_variant_in_struct_filter_label",
            "var_014_variant_in_struct/specs/var_014_variant_in_struct_read_all",
            "var_015_string_skipping/specs/var_015_string_skipping_filter_middle",
            "var_015_string_skipping/specs/var_015_string_skipping_read_all",
            "var_016_array_variant/specs/var_016_array_variant_filter_array_size",
            "var_016_array_variant/specs/var_016_array_variant_read_all",
            "var_017_map_variant/specs/var_017_map_variant_filter_by_id",
            "var_017_map_variant/specs/var_017_map_variant_read_all",
            "var_018_column_mapping/specs/var_018_column_mapping_filter_by_id",
            "var_018_column_mapping/specs/var_018_column_mapping_read_all",
            "var_019_schema_evolution/specs/var_019_schema_evolution_filter_new_column",
            "var_019_schema_evolution/specs/var_019_schema_evolution_read_all",
            "var_019_schema_evolution/specs/var_019_schema_evolution_read_v2_before_evolution",
            "var_020_time_travel/specs/var_020_time_travel_read_latest",
            "var_020_time_travel/specs/var_020_time_travel_read_v1",
            "var_020_time_travel/specs/var_020_time_travel_read_v2",
            "var_021_optimized/specs/var_021_optimized_filter_after_optimize",
            "var_021_optimized/specs/var_021_optimized_read_all",
            "var_022_stat_fields/specs/var_022_stat_fields_read_all",
            "var_all_json_types_read_all",
            "var_cdf_read/specs/var_cdf_read_read_all",
            "var_deeply_nested/specs/var_deeply_nested_read_all",
            "var_large_array/specs/var_large_array_read_all",
            "var_null_top_level/specs/var_null_top_level_filter_not_null",
            "var_null_top_level/specs/var_null_top_level_read_all",
            "var_numeric_precision/specs/var_numeric_precision_read_all",
            "var_predicate_non_variant/specs/var_predicate_non_variant_filter_category_A",
            "var_predicate_non_variant/specs/var_predicate_non_variant_read_all",
            "var_projection/specs/var_projection_project_id_data",
            "var_projection/specs/var_projection_read_all",
            "var_unicode_escapes/specs/var_unicode_escapes_read_all",
            "ds_variant_null_stats/specs/ds_variant_null_stats_hit_null_v_is_null",
            "ds_variant_null_stats/specs/ds_variant_null_stats_hit_null_v_struct_v_is_null",
            "ds_variant_null_stats/specs/ds_variant_null_stats_hit_v_is_not_null",
            "ds_variant_null_stats/specs/ds_variant_null_stats_hit_v_struct_v_not_null",
            "ds_variant_null_stats/specs/ds_variant_null_stats_miss_null_v_is_not_null",
            "ds_variant_null_stats/specs/ds_variant_null_stats_miss_null_v_struct_v_not_null",
            "ds_variant_null_stats/specs/ds_variant_null_stats_miss_v_is_null",
            "ds_variant_null_stats/specs/ds_variant_null_stats_miss_v_struct_v_is_null",
            "var_null_top_level/specs/var_null_top_level_filter_null",
        ],
    ),
    (
        "Kernel allows negative version, Spark rejects with DELTA_TABLE_RESTORE_VERSION_INVALID",
        &["dsReadVersionNegative/specs/dsReadVersionNegative_error"],
    ),
    (
        "void/NullType not supported in schema deserialization",
        &[
            "void_001_void_top_level/",
            "void_002_void_nested_struct/",
            "void_005_void_schema_evolution/",
            "void_006_void_multiple_columns/",
            "void_007_void_with_backticks/",
        ],
    ),
    (
        "Interval types not supported in schema deserialization",
        &[
            "intv_001_interval_ym_basic/",
            "intv_002_interval_dt_basic/",
            "intv_003_interval_partitioned/",
            "intv_004_interval_negative/",
            "intv_005_interval_mixed/",
            "intv_boundary_values/",
            "intv_sub_second/",
        ],
    ),
    (
        "Cannot fall back to log replay when checkpoint files are missing or incomplete",
        &[
            "corrupt_incomplete_multipart_checkpoint/",
            "ckp_incomplete_multipart/",
            "ckp_missing_checkpoint_file/",
        ],
    ),
    (
        "Cannot cast list to non-list data types during type widening",
        &[
            "tw_array_element/specs/tw_array_element_read_",
            "tw_map_key_value_widening/specs/tw_map_key_value_widening_read_all",
        ],
    ),
    (
        "Type widening metadata mismatch in nested struct fields",
        &[
            "tw_nested_field/specs/tw_nested_field_read_all",
            "tw_nested_field/specs/tw_nested_field_read_large_count",
        ],
    ),
    (
        "Schema deserialization fails for TimestampNTZ type",
        &["ds_multi_file_time/"],
    ),
    (
        "Column mapping id mode fails with None in final_fields_cols",
        &[
            "cm_id_matching_swapped/specs/cm_id_matching_swapped_select_",
            "cm_id_matching_nonexistent/specs/cm_id_matching_nonexistent_select_",
        ],
    ),
    (
        "Absolute-path DV has invalid percent-encoded path",
        &["dv_storage_type_p/specs/dv_storage_type_p_read_after_absolute_path_dv"],
    ),
    (
        "Fails on missing/empty delta log (no files in log segment)",
        &[
            "ct_empty_delta_log/specs/ct_empty_delta_log_snapshot",
            "ct_missing_delta_log/specs/ct_missing_delta_log_snapshot",
            "dseReadNonDeltaPath/specs/dseReadNonDeltaPath_snapshot",
        ],
    ),
    (
        "Accepts truncated log when initial commits are missing but CRC files exist",
        &["prod_truncated_log/"],
    ),
    (
        "Accepts checkpoint-only tables (no commits)",
        &["cp_checkpoint_only_table/specs/cp_checkpoint_only_table_error"],
    ),
    (
        "Projected column not found after column mapping/schema order change",
        &[
            "ds_schema_order_mismatch/specs/ds_schema_order_mismatch_single_col_last",
            "ds_with_dvs_edge/specs/ds_with_dvs_edge_proj_and_skip_with_dv",
            "dv_projection_with_pred/specs/dv_projection_with_pred_proj_and_pred",
        ],
    ),
    (
        "Does not reject unsupported column mapping mode",
        &["cm_err_003_invalid_mode/specs/cm_err_003_invalid_mode_error"],
    ),
    (
        "Reads corrupt/invalid commit or checkpoint without error",
        &[
            "corrupt_truncated_commit_json_error",
            "cp_err_missing_protocol/specs/cp_err_missing_protocol_error",
            "ct_corrupt_parquet/specs/ct_corrupt_parquet_error",
            "ct_invalid_json_error",
            "dsReadCorruptCheckpoint/specs/dsReadCorruptCheckpoint_error",
            "dsReadCorruptJson_error",
            "dsReadModifyCheckpoint/specs/dsReadModifyCheckpoint_error",
        ],
    ),
    (
        "Does not reject duplicate actions in commit",
        &[
            "ct_duplicate_metadata/specs/ct_duplicate_metadata_error",
            "ct_duplicate_protocol/specs/ct_duplicate_protocol_error",
            "err_duplicate_add_same_version/specs/err_duplicate_add_same_version_error",
        ],
    ),
    (
        "Snapshot construction succeeds even when data files are missing",
        &[
            "ct_missing_data_file/specs/ct_missing_data_file_error",
            "dv_err_002_missing_file/specs/dv_err_002_missing_file_error",
        ],
    ),
    (
        "Does not validate DV integrity",
        &[
            "dv_err_001_checksum/specs/dv_err_001_checksum_error",
            "dv_err_003_malformed_path/specs/dv_err_003_malformed_path_error",
            "err_dv_invalid_storage_type/specs/err_dv_invalid_storage_type_error",
            "err_add_and_remove_same_path_dv/specs/err_add_and_remove_same_path_dv_error",
        ],
    ),
    (
        "Does not validate schema integrity",
        &[
            "err_schema_empty/specs/err_schema_empty_error",
            "err_schema_invalid_json_error",
        ],
    ),
    (
        "Does not require version 0 to exist",
        &["err_missing_version_0/specs/err_missing_version_0_error"],
    ),
    (
        "Does not reject unknown reader features",
        &["ev_unknown_reader_feature/specs/ev_unknown_reader_feature_error"],
    ),
    (
        "Does not enforce time travel safety",
        &[
            "tt_blocked_beyond_retention/specs/tt_blocked_beyond_retention_error",
            "tt_after_vacuum/specs/tt_after_vacuum_error",
        ],
    ),
    (
        "_metadata.file_path column projection not supported",
        &["DV-003/specs/DV-003_metadata_file_path"],
    ),
    (
        "variantShredding feature not supported",
        &["pv_002_upgrade_to_current/specs/pv_002_upgrade_to_current_read_latest"],
    ),
    // Predicate evaluation fails due to incomplete type resolution, unsupported expressions,
    // or timestamp-based time travel not yet supported.
    (
        "Predicate evaluation or time travel failures",
        &[
            "cc_001_create_with_constraint_filter_constrained_col",
            "cdc_data_skipping_read_high",
            "cdc_data_skipping_read_low",
            "cks_histogram_read_value_lt_500",
            "cks_partitioned_read_part_0",
            "cks_partitioned_read_part_1",
            "cloneDeepPartitioned_readPartition",
            "cloneShallowPartitioned_readPartition",
            "cm_mode_name_read_by_price",
            "convertParquetPartitioned_readPartition",
            "cp_partitioned_read_part_0",
            "cp_partitioned_read_part_3",
            "ds_and_one_side_unsupported_hit_both_unsupported",
            "ds_and_one_side_unsupported_miss_a_supported",
            "ds_and_one_side_unsupported_miss_b_supported",
            "ds_and_two_fields_hit_and_a_b_like",
            "ds_and_two_fields_miss_and_b_like_2016",
            "ds_complex_nested_complex_and_or",
            "ds_complex_nested_complex_nested_or",
            "ds_complex_nested_complex_not",
            "ds_complex_nested_three_way_and",
            "ds_date_add_sub_hit_date_add_all",
            "ds_date_add_sub_hit_date_add_gt",
            "ds_date_add_sub_miss_date_add_future",
            "ds_datediff_hit_datediff_gt_30",
            "ds_datediff_hit_datediff_lt_20",
            "ds_float_special_values_hit_float_gt_0",
            "ds_float_special_values_hit_float_lt_0",
            "ds_generated_col_skipping_filter_generated_col",
            "ds_generated_col_skipping_filter_generated_col_range",
            "ds_in_list_in_list",
            "ds_in_list_in_list_single_file",
            "ds_in_nested_hit_code_in_1_2",
            "ds_in_nested_miss_code_in_99",
            "ds_in_set_hit_in_1",
            "ds_in_set_hit_in_12",
            "ds_in_set_miss_in_456",
            "ds_in_with_nulls_mixed_hit_in_1_null",
            "ds_in_with_nulls_mixed_miss_in_99_null",
            "ds_in_with_nulls_only_hit_in_1_2",
            "ds_in_with_nulls_only_hit_in_5",
            "ds_in_with_thresholds_hit_in_cross_files",
            "ds_in_with_thresholds_hit_in_small",
            "ds_in_with_thresholds_miss_in_no_match",
            "ds_isnull_complex_expr_hit_complex_or_and",
            "ds_long_strings_max_hit_like_A",
            "ds_long_strings_max_hit_like_C",
            "ds_long_strings_min_hit_like_A",
            "ds_missing_stats_graceful_filter_no_stats",
            "ds_missing_stats_graceful_filter_no_stats_range",
            "ds_month_function_hit_month_1",
            "ds_month_function_hit_month_6",
            "ds_month_function_miss_month_12",
            "ds_multi_file_ranges_hit_file1_and_2",
            "ds_multi_file_ranges_hit_file1_only",
            "ds_multi_file_ranges_hit_file2_and_3",
            "ds_multi_file_ranges_hit_file2_only",
            "ds_multi_file_ranges_hit_file3_only",
            "ds_multi_file_ranges_miss_all_gt_100",
            "ds_multi_file_ranges_miss_all_lt_0",
            "ds_not_in_not_in_1_2",
            "ds_not_in_not_in_3",
            "ds_not_in_not_in_all",
            "ds_null_safe_eq_nse_a_eq_1",
            "ds_null_safe_eq_nse_a_eq_null",
            "ds_null_safe_eq_nse_b_eq_null",
            "ds_null_safe_eq_nse_not_a_eq_1",
            "ds_null_safe_eq_nse_not_a_eq_null",
            "ds_nulls_mixed_hit_a_eq_1",
            "ds_nulls_mixed_hit_a_gt_0_is_null",
            "ds_nulls_mixed_hit_a_lt_0_is_null",
            "ds_nulls_mixed_hit_a_nse_1",
            "ds_nulls_mixed_hit_a_nse_null",
            "ds_nulls_mixed_hit_not_a_gt_0_is_null",
            "ds_nulls_mixed_hit_not_a_nse_1",
            "ds_nulls_mixed_hit_not_a_nse_null",
            "ds_nulls_mixed_miss_a_gt_1",
            "ds_nulls_mixed_miss_a_lt_1",
            "ds_nulls_mixed_miss_a_neq_1",
            "ds_nulls_mixed_miss_not_a_eq_1",
            "ds_nulls_nonnulls_only_hit_not_isnull",
            "ds_nulls_nonnulls_only_miss_and_isnull",
            "ds_nulls_nonnulls_only_miss_gt0_isnull",
            "ds_nulls_nonnulls_only_miss_lt0_isnull",
            "ds_nulls_nonnulls_only_miss_or_isnull",
            "ds_nulls_only_nonnull_miss_and_isnull",
            "ds_nulls_only_nonnull_miss_or_isnull",
            "ds_nulls_only_null_hit_a_gt_1_is_null",
            "ds_nulls_only_null_hit_not_a_nse_1",
            "ds_nulls_only_null_miss_a_eq_1",
            "ds_nulls_only_null_miss_a_gt_1",
            "ds_nulls_only_null_miss_a_lt_1",
            "ds_nulls_only_null_miss_a_neq_1",
            "ds_nulls_only_null_miss_a_nse_1",
            "ds_nulls_only_null_miss_not_a_eq_1",
            "ds_nulls_only_null_miss_not_a_gt_1_is_null",
            "ds_nulls_partial_stats_hit_b_and_a_isnull",
            "ds_nulls_partial_stats_hit_b_gt0_isnull",
            "ds_nulls_partial_stats_hit_b_lt0_isnull",
            "ds_nulls_partial_stats_hit_b_or_a_isnull",
            "ds_nulls_partial_stats_hit_not_a_isnull",
            "ds_nulls_partial_stats_miss_a_and_isnull",
            "ds_nulls_partial_stats_miss_a_gt0_isnull",
            "ds_nulls_partial_stats_miss_a_lt0_isnull",
            "ds_nulls_partial_stats_miss_a_or_isnull",
            "ds_numeric_types_hit_int_eq_25",
            "ds_numeric_types_hit_int_lt_50",
            "ds_numeric_types_miss_int_gt_200",
            "ds_or_one_side_unsupported_hit_a_unsupported",
            "ds_or_one_side_unsupported_hit_b_unsupported",
            "ds_or_two_fields_hit_or_a_b_like",
            "ds_or_two_fields_hit_or_a_b_like2",
            "ds_or_two_fields_miss_or_b_like_2016",
            "ds_partition_and_stats_data_filter_across_partitions",
            "ds_partition_and_stats_partition_and_data_filter",
            "ds_partitioned_hit_part_0",
            "ds_partitioned_hit_part_0_id_lt_10",
            "ds_partitioned_hit_part_1",
            "ds_partitioned_miss_part_99",
            "ds_starts_with_hit_like_a",
            "ds_starts_with_hit_like_all",
            "ds_starts_with_hit_like_ap",
            "ds_starts_with_hit_like_m",
            "ds_starts_with_hit_like_mic",
            "ds_starts_with_miss_like_xyz",
            "ds_starts_with_nested_hit_like_a",
            "ds_starts_with_nested_hit_like_all",
            "ds_starts_with_nested_hit_like_ap",
            "ds_starts_with_nested_hit_like_m",
            "ds_starts_with_nested_hit_like_mic",
            "ds_starts_with_nested_miss_like_xyz",
            "ds_stats_col_drop_filter_remaining_col",
            "ds_stats_col_rename_filter_renamed_col",
            "ds_stats_col_rename_filter_renamed_col_eq",
            "ds_stats_config_change_filter_indexed_col",
            "ds_stats_config_change_filter_non_indexed_col",
            "ds_string_patterns_hit_like_a",
            "ds_string_patterns_hit_like_all",
            "ds_string_patterns_hit_like_b",
            "ds_string_patterns_miss_like_z",
            "ds_timestamp_ntz_skipping_filter_ntz_eq",
            "ds_timestamp_ntz_skipping_filter_ntz_range",
            "ds_tinyint_smallint_hit_small_gt_500",
            "ds_tinyint_smallint_hit_tiny_lt_10",
            "ds_tinyint_smallint_miss_small_lt_50",
            "ds_tinyint_smallint_miss_tiny_gt_120",
            "ds_trunc_date_hit_trunc_year_2023",
            "ds_trunc_date_hit_trunc_year_2024",
            "ds_trunc_date_miss_trunc_year_2020",
            "ds_with_dvs_edge_1_filter_hits_dv_file",
            "ds_with_dvs_edge_1_skip_file_with_dv",
            "ds_with_dvs_edge_2_predicate_only_deleted_file",
            "ds_with_dvs_edge_2_predicate_spanning_deleted_file",
            "ds_with_dvs_edge_skip_exact_deleted",
            "ds_with_dvs_edge_skip_with_dv",
            "ds_year_function_hit_year_2023",
            "ds_year_function_hit_year_2024",
            "ds_year_function_miss_year_2020",
            "dv_insert_readback_read_new_rows_only",
            "dv_insert_readback_read_surviving_original",
            "dv_partition_pruning_prune_north_or_east",
            "dv_partition_pruning_prune_west_high_amount",
            "DV-002_version_1_id_gt_25",
            "DV-002_version_3_partCol_3_id_gt_25",
            "DV-002_version_4_partCol_eq_3",
            "ev_partitioned_read_partition_0",
            "ice_column_mapping_read_by_id",
            "pm_metadata_partitioned_read_date",
            "pm_protocol_3_7_read_value_gt_200",
            "pm_v2_checkpoints_read_lt_10",
            "restorePartitioned_readPartition",
            "tw_byte_to_int_read_gt_max_byte",
            "tw_byte_to_int_read_gt_max_short",
            "tw_decimal_precision_read_large_values",
            "tw_row_tracking_combo_read_wide_values",
            "tw_short_to_int_read_gt_max_short",
            "tw_with_dv_read_wide_values",
            "tw_with_partition_read_wide_values",
            "cc_002_show_tblproperties/specs/cc_002_show_tblproperties_filter_x",
            "cc_004_case_insensitive_drop/specs/cc_004_case_insensitive_drop_filter_negative",
            "cc_005_varchar_constraint/specs/cc_005_varchar_constraint_filter_short_string",
            "cc_006_basic_constraint/specs/cc_006_basic_constraint_filter_id",
            "cc_007_multiple_constraints/specs/cc_007_multiple_constraints_filter_amount",
            "cc_008_nested_constraint/specs/cc_008_nested_constraint_filter_nested_age",
            "cc_009_array_constraint/specs/cc_009_array_constraint_filter_array_size",
            "cc_011_compound_constraint/specs/cc_011_compound_constraint_filter_by_month",
            "cc_016_allowed_expressions/specs/cc_016_allowed_expressions_filter_num",
            "cc_020_decimal_constraint/specs/cc_020_decimal_constraint_filter_high_price",
            "cc_complex_expr/specs/cc_complex_expr_filter_age",
            "cc_null_aware/specs/cc_null_aware_filter_age",
            "cdc_predicates/specs/cdc_predicates_read_high_count",
            "ckp_after_100_commits/specs/ckp_after_100_commits_read_filtered",
            "ckp_corrupt_last_checkpoint/specs/ckp_corrupt_last_checkpoint_read_filtered",
            "ckp_struct_array_map/specs/ckp_struct_array_map_read_filtered",
            "ckp_v2_multiple_sidecars/specs/ckp_v2_multiple_sidecars_read_filtered",
            "ckp_wrong_version_hint/specs/ckp_wrong_version_hint_read_filtered",
            "cks_dv_in_crc/specs/cks_dv_in_crc_read_remaining",
            "cks_file_size_histogram_optimize/specs/cks_file_size_histogram_optimize_read_filtered",
            "cl_clustered_read/specs/cl_clustered_read_read_filtered",
            "cloneCheckpointData/specs/cloneCheckpointData_readFiltered",
            "cloneChecksumData/specs/cloneChecksumData_filterRange",
            "cloneHistoryAfterDml/specs/cloneHistoryAfterDml_filterDeleted",
            "cloneHistoryAfterDml/specs/cloneHistoryAfterDml_filterInserted",
            "cloneIdempotentData/specs/cloneIdempotentData_filterNew",
            "cloneShallowDvData/specs/cloneShallowDvData_readFiltered",
            "cloneSqlWithStats/specs/cloneSqlWithStats_filterStats",
            "cm_filter_pushdown_physical_names/specs/cm_filter_pushdown_physical_names_filter_a_eq_100_should_be_empty",
            "cm_filter_pushdown_physical_names/specs/cm_filter_pushdown_physical_names_filter_a_eq_1000",
            "cm_filter_pushdown_physical_names/specs/cm_filter_pushdown_physical_names_filter_c_eq_100",
            "cm_mode_id/specs/cm_mode_id_read_filtered",
            "cm_nested_columns/specs/cm_nested_columns_filter_nested",
            "cm_nested_struct_name/specs/cm_nested_struct_name_filter_nested_field",
            "cm_predicate_after_rename/specs/cm_predicate_after_rename_filter_eq_on_renamed_col",
            "cm_predicate_after_rename/specs/cm_predicate_after_rename_filter_on_renamed_col",
            "cm_predicate_on_readded/specs/cm_predicate_on_readded_pred_x_gt_150",
            "cp_classic_checkpoint/specs/cp_classic_checkpoint_read_filtered",
            "cp_last_checkpoint/specs/cp_last_checkpoint_read_filtered",
            "cr_multi_partition/specs/cr_multi_partition_filter_year",
            "cr_multi_partition/specs/cr_multi_partition_filter_year_month",
            "dcscArrayOfStruct/specs/dcscArrayOfStruct_read_filtered",
            "dcscBasicStruct/specs/dcscBasicStruct_read_filtered",
            "dcscDeeplyNestedStruct/specs/dcscDeeplyNestedStruct_read_deep_filter",
            "dcscMapWithStructValue/specs/dcscMapWithStructValue_read_filtered",
            "dcscNestedStruct/specs/dcscNestedStruct_read_filtered",
            "dcscStructPartitioned/specs/dcscStructPartitioned_read_age_filter",
            "dpReadPartitionAfterAppend/specs/dpReadPartitionAfterAppend_filterPartInCD",
            "dpReadPartitionDecimal/specs/dpReadPartitionDecimal_filterDecimalEq",
            "dpReadPartitionDecimal/specs/dpReadPartitionDecimal_filterDecimalGt",
            "dpReadPartitionIn/specs/dpReadPartitionIn_filterPartInAC",
            "dpReadPartitionIn/specs/dpReadPartitionIn_filterPartInBDE",
            "dpReadPartitionMixed/specs/dpReadPartitionMixed_filterPartAndValue",
            "dpReadPartitionMixed/specs/dpReadPartitionMixed_filterPartOrValue",
            "dpReadPartitionRange/specs/dpReadPartitionRange_filterPartBetween2And4",
            "dpReadPartitionRange/specs/dpReadPartitionRange_filterPartGt3",
            "dpReadPartitionTimestamp/specs/dpReadPartitionTimestamp_filterTsEq",
            "dpReadPartitionTimestamp/specs/dpReadPartitionTimestamp_filterTsGt",
            "ds_in_set/specs/ds_in_set_hit_in_123",
            "ds_not_in/specs/ds_not_in_not_in_outside",
            "ds_nulls_mixed/specs/ds_nulls_mixed_hit_a_eq_null",
            "ds_nulls_mixed/specs/ds_nulls_mixed_hit_not_a_eq_null",
            "ds_nulls_only_null/specs/ds_nulls_only_null_hit_a_eq_null",
            "ds_nulls_only_null/specs/ds_nulls_only_null_hit_a_nse_null",
            "ds_nulls_only_null/specs/ds_nulls_only_null_hit_not_a_eq_null",
            "ds_nulls_only_null/specs/ds_nulls_only_null_miss_not_a_nse_null",
            "ds_stats_after_drop/specs/ds_stats_after_drop_hit_c1_eq_1",
            "ds_stats_after_drop/specs/ds_stats_after_drop_hit_c10_gt_1_5",
            "ds_stats_after_drop/specs/ds_stats_after_drop_hit_c3_lt_1_5",
            "ds_stats_after_drop/specs/ds_stats_after_drop_hit_c4_gt_1_0",
            "ds_stats_after_drop/specs/ds_stats_after_drop_hit_c5_gte_ts",
            "ds_stats_after_drop/specs/ds_stats_after_drop_hit_c6_gte_ts_ntz",
            "ds_stats_after_drop/specs/ds_stats_after_drop_hit_c7_eq_date",
            "ds_stats_after_drop/specs/ds_stats_after_drop_miss_c10_gt_2_5",
            "ds_stats_after_drop/specs/ds_stats_after_drop_miss_c3_lt_0_5",
            "ds_stats_after_drop/specs/ds_stats_after_drop_miss_c1_eq_10",
            "ds_stats_after_drop/specs/ds_stats_after_drop_miss_c4_gt_5_0",
            "ds_stats_after_drop/specs/ds_stats_after_drop_miss_c5_gte_future",
            "ds_stats_after_drop/specs/ds_stats_after_drop_miss_c6_gte_future_ntz",
            "ds_stats_after_drop/specs/ds_stats_after_drop_miss_c7_eq_future",
            "ds_stats_after_rename/specs/ds_stats_after_rename_hit_cc1_eq_1",
            "ds_stats_after_rename/specs/ds_stats_after_rename_hit_cc10_gt_1_5",
            "ds_stats_after_rename/specs/ds_stats_after_rename_hit_cc2_eq_2",
            "ds_stats_after_rename/specs/ds_stats_after_rename_hit_cc3_lt_1_5",
            "ds_stats_after_rename/specs/ds_stats_after_rename_hit_cc4_gt_1_0",
            "ds_stats_after_rename/specs/ds_stats_after_rename_hit_cc5_gte_ts",
            "ds_stats_after_rename/specs/ds_stats_after_rename_hit_cc6_gte_ts_ntz",
            "ds_stats_after_rename/specs/ds_stats_after_rename_hit_cc7_eq_date",
            "ds_stats_after_rename/specs/ds_stats_after_rename_hit_cc8_hex_1111",
            "ds_stats_after_rename/specs/ds_stats_after_rename_hit_cc8_hex_3333",
            "ds_stats_after_rename/specs/ds_stats_after_rename_hit_cc9_false",
            "ds_stats_after_rename/specs/ds_stats_after_rename_hit_cc9_true",
            "ds_stats_after_rename/specs/ds_stats_after_rename_miss_cc10_gt_2_5",
            "ds_stats_after_rename/specs/ds_stats_after_rename_miss_cc3_lt_0_5",
            "ds_stats_after_rename/specs/ds_stats_after_rename_miss_cc1_eq_10",
            "ds_stats_after_rename/specs/ds_stats_after_rename_miss_cc2_eq_4",
            "ds_stats_after_rename/specs/ds_stats_after_rename_miss_cc4_gt_5_0",
            "ds_stats_after_rename/specs/ds_stats_after_rename_miss_cc5_gte_future",
            "ds_stats_after_rename/specs/ds_stats_after_rename_miss_cc6_gte_future_ntz",
            "ds_stats_after_rename/specs/ds_stats_after_rename_miss_cc7_eq_future",
            "ds_timestamp_microsecond/specs/ds_timestamp_microsecond_filter_exact_microsecond",
            "ds_timestamp_microsecond/specs/ds_timestamp_microsecond_filter_microsecond",
            "ds_timestamp_microsecond/specs/ds_timestamp_microsecond_read_all",
            "ds_typed_stats/specs/ds_typed_stats_hit_c1_eq_1",
            "ds_typed_stats/specs/ds_typed_stats_hit_c10_gt_1_5",
            "ds_typed_stats/specs/ds_typed_stats_hit_c2_eq_2",
            "ds_typed_stats/specs/ds_typed_stats_hit_c3_lt_1_5",
            "ds_typed_stats/specs/ds_typed_stats_hit_c4_gt_1_0",
            "ds_typed_stats/specs/ds_typed_stats_hit_c5_gte_ts",
            "ds_typed_stats/specs/ds_typed_stats_hit_c6_gte_ts_ntz",
            "ds_typed_stats/specs/ds_typed_stats_hit_c7_eq_date",
            "ds_typed_stats/specs/ds_typed_stats_hit_c8_hex_1111",
            "ds_typed_stats/specs/ds_typed_stats_hit_c8_hex_3333",
            "ds_typed_stats/specs/ds_typed_stats_hit_c9_false",
            "ds_typed_stats/specs/ds_typed_stats_hit_c9_true",
            "ds_typed_stats/specs/ds_typed_stats_miss_c10_gt_2_5",
            "ds_typed_stats/specs/ds_typed_stats_miss_c3_lt_0_5",
            "ds_typed_stats/specs/ds_typed_stats_miss_c1_eq_10",
            "ds_typed_stats/specs/ds_typed_stats_miss_c2_eq_4",
            "ds_typed_stats/specs/ds_typed_stats_miss_c4_gt_5_0",
            "ds_typed_stats/specs/ds_typed_stats_miss_c5_gte_future",
            "ds_typed_stats/specs/ds_typed_stats_miss_c6_gte_future_ntz",
            "ds_typed_stats/specs/ds_typed_stats_miss_c7_eq_future",
            "dseReadWithStats/specs/dseReadWithStats_filterIdEq",
            "dseReadWithStats/specs/dseReadWithStats_filterIdRange",
            "dsReadAndPredicate/specs/dsReadAndPredicate_filterAnd",
            "dsReadBetweenPredicate/specs/dsReadBetweenPredicate_readBetween",
            "dsReadCdcEnabled/specs/dsReadCdcEnabled_filterDeleted",
            "dsReadCdcEnabled/specs/dsReadCdcEnabled_filterUpdated",
            "dsReadDateType/specs/dsReadDateType_readAfterJune",
            "dsReadDecimalType/specs/dsReadDecimalType_readExpensive",
            "dsReadEmptyPartition/specs/dsReadEmptyPartition_readNonExistentPartition",
            "dsReadInPredicate/specs/dsReadInPredicate_readInSet",
            "dsReadLikePredicate/specs/dsReadLikePredicate_filterLikeAlp",
            "dsReadOrPredicate/specs/dsReadOrPredicate_filterOr",
            "dsReadPartitioned/specs/dsReadPartitioned_readPartition0",
            "dsReadPartitioned/specs/dsReadPartitioned_readPartition3",
            "dsReadUpdateThenRead/specs/dsReadUpdateThenRead_readUpdated",
            "dsReadWithPredicate/specs/dsReadWithPredicate_readFiltered",
            "dv_checkpoint_read/specs/dv_checkpoint_read_read_filtered",
            "dv_column_mapping_read/specs/dv_column_mapping_read_filter_on_value",
            "dv_predicate_on_deleted/specs/dv_predicate_on_deleted_predicate_only_deleted",
            "dv_predicate_on_deleted/specs/dv_predicate_on_deleted_predicate_surviving",
            "DV-004/specs/DV-004_filter_300_787_239",
            "DV-011/specs/DV-011_filter_col1_eq_2",
            "ev_batch_read/specs/ev_batch_read_read_filtered",
            "ev_unknown_writer_feature/specs/ev_unknown_writer_feature_read_filtered",
            "fpe_space_in_path/specs/fpe_space_in_path_filter_id_eq_1",
            "gc_append_data/specs/gc_append_data_filter_partition",
            "gc_complex_type/specs/gc_complex_type_filter_sum",
            "gc_delete/specs/gc_delete_filter_remaining",
            "gc_insert_by_name/specs/gc_insert_by_name_filter_c2_g",
            "gc_merge_insert_star/specs/gc_merge_insert_star_filter_merged",
            "gc_partitioned/specs/gc_partitioned_filter_2024",
            "gc_update_source/specs/gc_update_source_filter_c2_g_updated",
            "ic_010_restore_partitioned/specs/ic_010_restore_partitioned_filter_partition_1",
            "ic_bigint_type/specs/ic_bigint_type_filter_high",
            "ice_complex_types/specs/ice_complex_types_filter_id",
            "ice_with_dv/specs/ice_with_dv_filter_remaining",
            "lc_with_schema/specs/lc_with_schema_read_filtered",
            "log_replay_dv_key_dedup/specs/log_replay_dv_key_dedup_filter_remaining",
            "ntz_basic/specs/ntz_basic_filter_ntz",
            "ntz_far_past/specs/ntz_far_past_filter_before_1900",
            "ntz_partition/specs/ntz_partition_filter_partition",
            "ntz_partition/specs/ntz_partition_filter_partition_range",
            "ntz_stats/specs/ntz_stats_filter_ntz_late_year",
            "ntz_stats/specs/ntz_stats_filter_ntz_range",
            "part_date_type/specs/part_date_type_filter_date",
            "part_date_type/specs/part_date_type_filter_date_range",
            "part_multi_column/specs/part_multi_column_filter_a",
            "part_multi_column/specs/part_multi_column_filter_a_b",
            "part_multi_column/specs/part_multi_column_filter_all_three",
            "ps_both_stats_and_parsed/specs/ps_both_stats_and_parsed_filter_category",
            "ps_nested_fields/specs/ps_nested_fields_filter_nested_age",
            "ps_partitioned/specs/ps_partitioned_filter_partition",
            "ps_v2_checkpoint/specs/ps_v2_checkpoint_filter_id",
            "pve_byte_partition/specs/pve_byte_partition_filter_max",
            "pve_byte_partition/specs/pve_byte_partition_filter_min",
            "pve_byte_partition/specs/pve_byte_partition_filter_positive",
            "pve_decimal_partition/specs/pve_decimal_partition_filter_boundary",
            "pve_decimal_partition/specs/pve_decimal_partition_filter_eq",
            "pve_decimal_partition/specs/pve_decimal_partition_filter_positive",
            "pve_float_partition/specs/pve_float_partition_filter_eq",
            "pve_float_partition/specs/pve_float_partition_filter_positive",
            "pve_multi_partition_cols/specs/pve_multi_partition_cols_filter_all_three",
            "pve_multi_partition_cols/specs/pve_multi_partition_cols_filter_int_range",
            "pve_multi_partition_cols/specs/pve_multi_partition_cols_filter_str_and_int",
            "pve_short_partition/specs/pve_short_partition_filter_max",
            "pve_short_partition/specs/pve_short_partition_filter_min",
            "pve_short_partition/specs/pve_short_partition_filter_range",
            "pve_timestamp_ntz_partition/specs/pve_timestamp_ntz_partition_filter_eq",
            "pve_timestamp_ntz_partition/specs/pve_timestamp_ntz_partition_filter_range",
            "pve_timestamp_partition/specs/pve_timestamp_partition_filter_eq",
            "pve_timestamp_partition/specs/pve_timestamp_partition_filter_range",
            "restoreMultipleVersions/specs/restoreMultipleVersions_filterMissing",
            "restoreMultipleVersions/specs/restoreMultipleVersions_filterV0",
            "restoreWithDv/specs/restoreWithDv_filterRestored",
            "rt_filter_read/specs/rt_filter_read_read_filtered",
            "se_add_col_pred_eq/specs/se_add_col_pred_eq_pred_score_eq_0",
            "se_add_col_pred_eq/specs/se_add_col_pred_eq_pred_score_eq_95",
            "se_add_col_pred_null/specs/se_add_col_pred_null_pred_score_gt_90",
            "se_drop_col_pred/specs/se_drop_col_pred_pred_id_gt_2",
            "se_readd_pred/specs/se_readd_pred_pred_x_eq_200",
            "se_rename_pred/specs/se_rename_pred_pred_full_name_like",
            "st_decimal_stats/specs/st_decimal_stats_filter_decimal_eq",
            "st_decimal_stats/specs/st_decimal_stats_filter_decimal_range",
            "st_float_nan_inf/specs/st_float_nan_inf_filter_finite",
            "st_float_nan_inf/specs/st_float_nan_inf_filter_id_range",
            "st_indexed_cols/specs/st_indexed_cols_filter_col1",
            "st_indexed_cols/specs/st_indexed_cols_filter_col2",
            "st_indexed_cols/specs/st_indexed_cols_filter_col3",
            "st_multi_file_stats/specs/st_multi_file_stats_filter_part_0",
            "st_multi_file_stats/specs/st_multi_file_stats_filter_part_5",
            "st_multi_file_stats/specs/st_multi_file_stats_filter_part_range",
            "st_nested_stats/specs/st_nested_stats_filter_nested_category",
            "st_numeric_stats/specs/st_numeric_stats_filter_double_gt",
            "st_numeric_stats/specs/st_numeric_stats_filter_int_eq",
            "st_string_stats/specs/st_string_stats_filter_string_like",
            "st_tinyint_smallint/specs/st_tinyint_smallint_filter_smallint_negative",
            "st_tinyint_smallint/specs/st_tinyint_smallint_filter_tinyint_range",
            "stats_empty_string/specs/stats_empty_string_filter_id_eq_3",
            "stats_missing_entirely/specs/stats_missing_entirely_filter_id_eq_2",
            "stats_numrecords_only/specs/stats_numrecords_only_filter_id_eq_1",
            "stats_partition_col_no_stats/specs/stats_partition_col_no_stats_filter_by_data_col",
            "tntz_column_mapping/specs/tntz_column_mapping_filter_ntz",
            "tntz_epoch/specs/tntz_epoch_filter_epoch",
            "tntz_partition_filter/specs/tntz_partition_filter_filter_exact_partition",
            "tntz_partition_filter/specs/tntz_partition_filter_filter_range_partition",
            "tt_dv_between_versions/specs/tt_dv_between_versions_read_v2_filtered",
            "tt_partition_filter/specs/tt_partition_filter_v0_part_0_or_1",
            "tw_colmap_rename/specs/tw_colmap_rename_filter_wide",
            "tw_stats_after_change/specs/tw_stats_after_change_predicate_cross_range",
            "tw_stats_after_change/specs/tw_stats_after_change_predicate_new_range",
            "tw_stats_after_change/specs/tw_stats_after_change_predicate_old_range",
            "var_022_stat_fields/specs/var_022_stat_fields_filter_variant_field",
        ],
    ),
    (
        "Timestamp-based time travel not yet supported",
        &[
            "ict_basic_read_v0_ts",
            "ict_dml_read_v0_ts",
            "ict_enable_later_read_v0_no_ict_ts",
            "ict_enable_later_read_v1_no_ict_ts",
            "ict_enable_later_read_v3_with_ict_ts",
            "ict_enabled_mid_lifecycle_read_v0_no_ict_ts",
            "ict_enabled_mid_lifecycle_read_v1_no_ict_ts",
            "ict_from_crc_read_v0_ts",
            "ict_from_crc_read_v1_ts",
            "ict_multiple_commits_read_v0_ts",
            "ict_multiple_commits_read_v1_ts",
            "ict_multiple_commits_read_v2_ts",
            "ict_time_travel_read_v0_ts",
            "ict_time_travel_read_v1_ts",
            "ict_time_travel_read_v2_ts",
            "ict_timestamp_resolution_edges_read_ts_v2_exact",
            "ict_timestamp_resolution_edges_read_ts_v2_minus_1ms",
            "ict_timestamp_resolution_edges_read_ts_v2_plus_1ms",
            "ict_timestamp_resolution_edges_read_ts_v3_exact",
            "ict_timestamp_resolution_edges_read_ts_v3_minus_1ms",
            "ict_with_checkpoint_read_v1_ts",
            "ict_with_checkpoint_read_v3_ts",
            "tt_at_syntax_timestamp_v0",
            "tt_at_syntax_timestamp_v1",
            "tt_column_defaults_timestamp_v0_empty",
            "tt_column_defaults_timestamp_v1_null",
            "tt_exact_timestamp_version_0_exact_ts",
            "tt_exact_timestamp_version_1_exact_ts",
            "tt_multi_version_scans_timestamp_v0",
            "tt_multi_version_scans_timestamp_v1",
            "tt_partition_evolution_timestamp_v0_old_partition",
            "tt_partition_evolution_timestamp_v1_new_partition",
            "tt_relation_caching_timestamp_v0",
            "tt_relation_caching_timestamp_v1",
            "tt_schema_evolution_timestamp_v0_old_schema",
            "tt_schema_evolution_timestamp_v1_new_schema",
            "tt_sql_syntax_timestamp_v0",
            "tt_sql_syntax_timestamp_v1",
            "tt_timestamp_between_commits_timestamp_v0",
            "tt_timestamp_between_commits_timestamp_v1",
            "tt_timestamp_between_commits_timestamp_v2",
            "tt_version_read_timestamp_v0",
            "tt_version_read_timestamp_v1",
            "tt_version_read_timestamp_v2",
        ],
    ),
];

fn acceptance_workloads_test(spec_path: &Path) -> datatest_stable::Result<()> {
    let spec_path_raw = format!(
        "{}/{}",
        env!["CARGO_MANIFEST_DIR"],
        spec_path.to_str().unwrap()
    );
    let spec_path_abs = std::fs::canonicalize(&spec_path_raw)
        .unwrap_or_else(|_| std::path::PathBuf::from(&spec_path_raw));
    let spec_path_str = spec_path_abs.to_string_lossy().to_string();

    // Check expected kernel failures FIRST (path matching only - these need to
    // actually run to assert kernel still fails). Skip list checked second.
    let expected_failure = EXPECTED_KERNEL_FAILURES
        .iter()
        .find(|(_, patterns)| patterns.iter().any(|p| spec_path_str.contains(p)));

    if expected_failure.is_none() && should_skip_test(&spec_path_str).is_some() {
        return Ok(());
    }

    // Load spec and test case once
    let content = std::fs::read_to_string(&spec_path_abs).expect("Failed to read spec file");
    let spec: Spec = serde_json::from_str(&content).expect("Failed to parse spec file");

    // Try to load test case. For error tests with invalid table_info (e.g. duplicate columns),
    // we may not be able to load it. In that case, skip the test - the invalid schema in
    // table_info indicates the error is detected at snapshot construction time. For non-error
    // tests with unsupported types (e.g. time(6)), skip them as well.
    let (test_case, workload_name) = match test_case_from_spec_path(&spec_path_abs) {
        Ok(tc) => tc,
        Err(e) => {
            let is_error_test = match &spec {
                Spec::Read(read_spec) => {
                    matches!(read_spec.expected, Some(ReadExpected::Error { .. }))
                }
                Spec::SnapshotConstruction(snapshot_spec) => {
                    matches!(snapshot_spec.expected, Some(SnapshotExpected::Error { .. }))
                }
            };
            // Skip if: (1) error test with invalid table_info, or (2) unsupported type in schema
            if is_error_test || e.contains("Unsupported Delta table type") {
                return Ok(());
            }
            panic!("Failed to load test case: {:?}", e);
        }
    };
    let expected_dir = test_case.expected_dir(&workload_name);

    let table_root = test_case.table_root().expect("Failed to get table URL");
    let engine = test_utils::create_default_engine(&table_root).expect("Failed to create engine");

    // Expected kernel failures: assert kernel DOES fail
    if let Some((reason, _)) = expected_failure {
        match execute_and_validate_workload(engine, &table_root, &spec, &expected_dir) {
            Err(_) => { /* Failure is expected */ }
            Ok(_) => panic!(
                "Workload '{workload_name}' was expected to fail but succeeded! \
                 Reason: {reason}. Remove from EXPECTED_KERNEL_FAILURES!"
            ),
        }
        return Ok(());
    }

    execute_and_validate_workload(engine, &table_root, &spec, &expected_dir)
        .unwrap_or_else(|e| panic!("Workload '{}' failed: {}", workload_name, e));
    Ok(())
}

datatest_stable::harness! {
    {
        test = acceptance_workloads_test,
        root = "workloads/",
        pattern = r"specs/.*\.json$"
    },
}
