//! The [`CoroutineSM`] driver: compiles [`PhaseYield`] sequences into the
//! [`StateMachine`] contract.
//!
//! Protocol is strictly 1:1: each yield carries one [`PhaseOperation`], the driver hands it
//! to the engine via [`StateMachine::get_operation`], and the engine outcome flows back as a
//! [`PhaseResume`] on [`StateMachine::advance`]. Zero-yield coroutines are allowed; they
//! return [`AdvanceResult::Done`] on the first advance.
//!
//! Multi-plan phases use one [`PhaseOperation::Plans`] with several plans and recover
//! per-plan outputs from the resulting [`PhaseState`] via the respective extractors.
//!
//! Built on [`genawaiter2`], which panics on coroutine protocol misuse (awaiting a non-yield
//! future, retaining a `Co` after return). The no-panic rule is preserved because the only
//! path to `Co::yield_` is through [`Context::execute`]; SM bodies are `pub(crate)`-only and
//! FFI sees them through `Box<dyn StateMachine>`, so the panic paths are unreachable
//! externally.

use std::future::Future;

use genawaiter2::sync::GenBoxed;
use genawaiter2::GeneratorState;
use uuid::Uuid;

use super::super::engine_error::EngineError;
use super::super::phase_operation::PhaseOperation;
use super::super::phase_state::PhaseState;
use super::super::state_machine::{AdvanceResult, StateMachine};
use super::context::{PhaseCo, PhaseResume, PhaseYield};
use crate::bail_delta;
use crate::plans::errors::{DeltaError, DeltaErrorCode};

type InnerGen<R> = GenBoxed<PhaseYield, PhaseResume, Result<R, DeltaError>>;

/// A state machine driven by a stackless coroutine (via [`genawaiter2`]).
///
/// At each phase the body yields a single [`PhaseYield`] (operation + static phase name + live
/// relation snapshot) and awaits the engine outcome. The driver shuttles operations to
/// [`StateMachine::get_operation`] and resumes the body with the matching [`PhaseResume`] on
/// [`StateMachine::advance`].
///
/// # Identity
///
/// Every `CoroutineSM` carries a fresh `sm_id: Uuid` and a static `sm_kind` label (the kernel
/// SM's logical kind: `"scan_metadata"`, `"full_state"`, ...). Together with the per-phase name
/// available via [`StateMachine::phase_name`] these form the `(sm_id, sm_kind, phase_name)`
/// identity tuple used to correlate engine activity across the SM boundary.
///
/// `sm_id` is generated by the driver and passed into the producer closure, so SM bodies can
/// thread it into a [`RelationRegistry`](crate::plans::ir::RelationRegistry) -- handles minted by
/// that registry then deterministically embed `sm_id`, giving every materialized relation a
/// stable identity rooted at the owning SM.
pub struct CoroutineSM<R: Send + 'static> {
    gen: InnerGen<R>,
    /// Where the SM is positioned. `Yielded` while engine work is pending; `ResultReady` when the
    /// body completed without ever yielding (the next `advance` hands the stored result back);
    /// `Done` once `advance` has returned the terminal result.
    state: SmPosition<R>,
    sm_id: Uuid,
    sm_kind: &'static str,
}

/// Internal positioning of a [`CoroutineSM`]. Drives the [`StateMachine`] contract.
enum SmPosition<R> {
    /// A phase is queued; engine work pending.
    Yielded(PhaseYield),
    /// Body has produced its terminal result; awaiting `advance` to hand it back. Reached only by
    /// zero-yield SMs (multi-yield SMs skip through this state inside `advance` and transition
    /// straight to `Done`).
    ResultReady(Result<R, DeltaError>),
    /// Result has been consumed; terminal sink.
    Done,
}

impl<R: Send + 'static> CoroutineSM<R> {
    /// Construct a coroutine state machine and run the producer to its first yield (or to
    /// completion).
    ///
    /// `sm_kind` labels the SM's logical kind for diagnostics (e.g. `"scan_metadata"`); the
    /// driver mints a fresh `sm_id` and threads it into the producer closure so the body can
    /// build a [`RelationRegistry`](crate::plans::ir::RelationRegistry) rooted at this SM.
    ///
    /// If the producer yields, the first yield becomes the initial [`PhaseYield`] returned by
    /// [`StateMachine::get_operation`]. If it completes without yielding, the terminal result is
    /// stored and handed back from the first [`StateMachine::advance`] call -- callers don't need
    /// to special-case zero-yield SMs.
    pub(crate) fn new<F, Fut>(sm_kind: &'static str, producer: F) -> Result<Self, DeltaError>
    where
        F: FnOnce(PhaseCo, Uuid) -> Fut + Send + 'static,
        Fut: Future<Output = Result<R, DeltaError>> + Send + 'static,
    {
        let sm_id = Uuid::new_v4();
        let mut gen: InnerGen<R> = GenBoxed::new_boxed(move |co| producer(co, sm_id));
        // genawaiter2's `Gen<Y, R, F>` exposes only `resume_with(R)`; the first resume arg is
        // discarded because no future is yet awaiting it. We pass an inert
        // `Ok(PhaseState::empty())` sentinel that the body would never observe.
        let state = match gen.resume_with(PhaseResume(Ok(PhaseState::empty()))) {
            GeneratorState::Yielded(phase) => SmPosition::Yielded(phase),
            GeneratorState::Complete(result) => SmPosition::ResultReady(result),
        };
        Ok(Self {
            gen,
            state,
            sm_id,
            sm_kind,
        })
    }

    /// `true` once the coroutine has terminated and [`advance`](Self::advance) has handed out its
    /// final result.
    pub fn is_done(&self) -> bool {
        matches!(self.state, SmPosition::Done)
    }

    /// Fresh per-instance identifier. Stable across the lifetime of this SM and embedded in every
    /// [`RelationHandle`](crate::plans::ir::nodes::RelationHandle) the body materializes through
    /// its [`RelationRegistry`](crate::plans::ir::RelationRegistry).
    pub fn sm_id(&self) -> Uuid {
        self.sm_id
    }

    /// Static label for the SM's logical kind (e.g. `"scan_metadata"`, `"full_state"`).
    pub fn sm_kind(&self) -> &'static str {
        self.sm_kind
    }
}

impl<R: Send + 'static> StateMachine for CoroutineSM<R> {
    type Result = R;

    fn get_operation(&mut self) -> Result<PhaseOperation, DeltaError> {
        match &self.state {
            SmPosition::Yielded(phase) => Ok(phase.operation.clone()),
            SmPosition::ResultReady(_) => bail_delta!(
                DeltaErrorCode::DeltaCommandInvariantViolation,
                "CoroutineSM::get_operation: zero-yield SM has no pending operation; \
                 call advance() to receive the terminal result",
            ),
            SmPosition::Done => bail_delta!(
                DeltaErrorCode::DeltaCommandInvariantViolation,
                "CoroutineSM::get_operation: state machine already completed",
            ),
        }
    }

    fn advance(
        &mut self,
        result: Result<PhaseState, EngineError>,
    ) -> Result<AdvanceResult<R>, DeltaError> {
        match std::mem::replace(&mut self.state, SmPosition::Done) {
            SmPosition::ResultReady(value) => value.map(AdvanceResult::Done),
            SmPosition::Done => bail_delta!(
                DeltaErrorCode::DeltaCommandInvariantViolation,
                "CoroutineSM::advance: cannot advance, already completed",
            ),
            SmPosition::Yielded(_) => match self.gen.resume_with(PhaseResume(result)) {
                GeneratorState::Yielded(next) => {
                    self.state = SmPosition::Yielded(next);
                    Ok(AdvanceResult::Continue)
                }
                GeneratorState::Complete(final_result) => final_result.map(AdvanceResult::Done),
            },
        }
    }

    fn phase_name(&self) -> &'static str {
        match &self.state {
            SmPosition::Yielded(phase) => phase.phase_name,
            SmPosition::ResultReady(_) | SmPosition::Done => "done",
        }
    }

    fn live_relations(&self) -> Vec<String> {
        match &self.state {
            SmPosition::Yielded(phase) => phase.live_relations.clone(),
            SmPosition::ResultReady(_) | SmPosition::Done => Vec::new(),
        }
    }
}

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use super::*;
    use crate::plans::ir::nodes::{RelationHandle, ScanNode, SinkType};
    use crate::plans::ir::{DeclarativePlanNode, Plan, RelationRegistry};
    use crate::plans::state_machines::framework::coroutine::context::Context;
    use crate::plans::state_machines::framework::engine_error::{EngineError, EngineErrorKind};

    // A throwaway plan whose identity we don't care about — the SM tests
    // only look at the shape of `PhaseOperation`, not what's inside.
    fn toy_plan() -> Plan {
        let schema = Arc::new(crate::schema::StructType::new_unchecked(Vec::<
            crate::schema::StructField,
        >::new()));
        let root = DeclarativePlanNode::Scan(ScanNode::new(
            crate::plans::ir::nodes::FileType::Parquet,
            Vec::new(),
            schema.clone(),
        ));
        let sink = SinkType::Relation(RelationHandle::fresh("toy", schema));
        Plan::new(root, sink)
    }

    /// Drive a two-phase SM: yield op A, observe empty PhaseState, yield op B, complete.
    #[test]
    fn two_phase_sm_executes_in_sequence() {
        let mut sm = CoroutineSM::<i64>::new("test", |mut co, sm_id| async move {
            let mut ctx = Context::new(&mut co, RelationRegistry::new(sm_id, ""));
            let _ = ctx
                .execute(PhaseOperation::Plans(vec![toy_plan()]), "phase_a")
                .await
                .map_err(|e| e.into_delta(DeltaErrorCode::DeltaCommandInvariantViolation))?;
            let _ = ctx
                .execute(PhaseOperation::Plans(vec![toy_plan()]), "phase_b")
                .await
                .map_err(|e| e.into_delta(DeltaErrorCode::DeltaCommandInvariantViolation))?;
            Ok(42)
        })
        .unwrap();

        assert_eq!(sm.sm_kind(), "test");

        assert_eq!(sm.phase_name(), "phase_a");
        let op = sm.get_operation().unwrap();
        match op {
            PhaseOperation::Plans(plans) => assert_eq!(plans.len(), 1),
            _ => panic!("expected Plans"),
        }

        let r = sm.advance(Ok(PhaseState::empty())).unwrap();
        assert!(matches!(r, AdvanceResult::Continue));
        assert_eq!(sm.phase_name(), "phase_b");

        let op = sm.get_operation().unwrap();
        assert!(matches!(op, PhaseOperation::Plans(p) if p.len() == 1));

        let r = sm.advance(Ok(PhaseState::empty())).unwrap();
        match r {
            AdvanceResult::Done(v) => assert_eq!(v, 42),
            _ => panic!("expected Done"),
        }
        assert!(sm.is_done());
    }

    /// Multiple plans in a single phase are passed through verbatim.
    #[test]
    fn multi_plan_phase_executes_in_one_engine_call() {
        let mut sm = CoroutineSM::<()>::new("test", |mut co, sm_id| async move {
            let mut ctx = Context::new(&mut co, RelationRegistry::new(sm_id, ""));
            let _ = ctx
                .execute(PhaseOperation::Plans(vec![toy_plan(), toy_plan()]), "ab")
                .await
                .map_err(|e| e.into_delta(DeltaErrorCode::DeltaCommandInvariantViolation))?;
            Ok(())
        })
        .unwrap();

        let op = sm.get_operation().unwrap();
        match op {
            PhaseOperation::Plans(plans) => assert_eq!(plans.len(), 2),
            _ => panic!("expected Plans"),
        }

        let r = sm.advance(Ok(PhaseState::empty())).unwrap();
        assert!(matches!(r, AdvanceResult::Done(())));
    }

    /// `live_relations()` reflects the registry snapshot at the most recent yield boundary.
    #[test]
    fn live_relations_surfaces_registry_snapshot_at_yield() {
        let mut sm = CoroutineSM::<()>::new("test", |mut co, sm_id| async move {
            let mut ctx = Context::new(&mut co, RelationRegistry::new(sm_id, ""));
            let schema = Arc::new(crate::schema::StructType::new_unchecked(Vec::<
                crate::schema::StructField,
            >::new(
            )));
            let _ = ctx.register_relation_sink("commits", schema.clone())?;
            let _ = ctx.register_relation_sink("checkpoints", schema)?;
            let _ = ctx
                .execute(PhaseOperation::Plans(vec![toy_plan()]), "p")
                .await
                .map_err(|e| e.into_delta(DeltaErrorCode::DeltaCommandInvariantViolation))?;
            Ok(())
        })
        .unwrap();

        // First yield observed: snapshot should contain both registered relations, sorted.
        assert_eq!(
            sm.live_relations(),
            vec!["checkpoints".to_string(), "commits".to_string()]
        );

        let _ = sm.advance(Ok(PhaseState::empty())).unwrap();
        // After completion, the snapshot is empty.
        assert!(sm.live_relations().is_empty());
        assert!(sm.is_done());
    }

    /// Engine errors flow through as `Err(EngineError)` on resume; the SM body receives them and
    /// decides what to do.
    #[test]
    fn engine_error_flows_to_body_as_resume_err() {
        let mut sm = CoroutineSM::<String>::new("test", |mut co, sm_id| async move {
            let mut ctx = Context::new(&mut co, RelationRegistry::new(sm_id, ""));
            match ctx
                .execute(PhaseOperation::Plans(vec![toy_plan()]), "p")
                .await
            {
                Err(e) => Ok(format!("got: {}", e.kind)),
                Ok(_) => panic!("expected engine error"),
            }
        })
        .unwrap();

        let _ = sm.get_operation().unwrap();
        let err = EngineError::new(EngineErrorKind::FileNotFound { path: "/x".into() });
        let r = sm.advance(Err(err)).unwrap();
        match r {
            AdvanceResult::Done(s) => assert!(s.contains("file not found: /x")),
            _ => panic!("expected Done"),
        }
    }

    /// Zero-yield coroutines are allowed: the first `advance` call hands the stored terminal
    /// value back. Useful for SMs that compute their plans entirely up-front and have no
    /// intermediate engine work.
    #[test]
    fn zero_phase_coroutine_returns_value_on_first_advance() {
        let mut sm = CoroutineSM::<i32>::new("test", |_co, _sm_id| async move { Ok(7) }).unwrap();
        assert!(sm.get_operation().is_err());
        let r = sm.advance(Ok(PhaseState::empty())).unwrap();
        match r {
            AdvanceResult::Done(v) => assert_eq!(v, 7),
            _ => panic!("expected Done"),
        }
        assert!(sm.is_done());
    }
}
