[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
delta_kernel = { path = "../kernel" }
delta-kernel-engine = { path = "../delta-kernel-engine", features = [ "arrow-55" ] }
