on: [pull_request_target]
name: Benchmarking PR performance

env:
  # See build.yml top-level comment for why we use both sccache and Swatinem/rust-cache.
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  runBenchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: Swatinem/rust-cache@v2
      - uses: boa-dev/criterion-compare-action@v3
        env:
          BENCH_TAGS: base
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branchName: ${{ github.base_ref }}
          cwd: benchmarks
          benchName: workload_bench
      - name: sccache stats
        if: always()
        run: sccache --show-stats
