[package]
name = "variant"
description = "Low-level library related to the Variant data type."
edition = "2021"

[dependencies]
serde_json = { version = "1.0", features = ["arbitrary_precision"] }

[lib]
crate-type = ["lib"]
